services:
  db:
    image: postgres:15-alpine
    container_name: ${DB_CONTAINER_NAME:-drivee_nl2sql_db}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-drivee_nl2sql}
    ports:
      - "${PGHOST_PORT:-15432}:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-drivee_nl2sql}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
