CREATE TABLE IF NOT EXISTS orders (
    city_id INT,
    order_id VARCHAR(50),
    tender_id VARCHAR(50),
    user_id VARCHAR(50),
    driver_id VARCHAR(50),
    offset_hours INT,
    status_order VARCHAR(20),
    status_tender VARCHAR(20),
    order_timestamp TIMESTAMP,
    tender_timestamp TIMESTAMP,
    driveraccept_timestamp TIMESTAMP,
    driverarrived_timestamp TIMESTAMP,
    driverstarttheride_timestamp TIMESTAMP,
    driverdone_timestamp TIMESTAMP,
    clientcancel_timestamp TIMESTAMP,
    drivercancel_timestamp TIMESTAMP,
    order_modified_local TIMESTAMP,
    cancel_before_accept_local TIMESTAMP,
    distance_in_meters FLOAT,
    duration_in_seconds FLOAT,
    price_order_local FLOAT,
    price_tender_local FLOAT,
    price_start_local FLOAT
);
